apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: nodejs-sample
  namespace: insights-qa
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: my-application2
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: nodejs-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: nodejs-sample-
      labels:
        build.appstudio.openshift.io/application: my-application2
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: nodejs-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: insights-qa
    spec:
      params:
      - name: git-url
        value: https://github.com/nodeshift-starters/devfile-sample.git
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:insights-qa-nodejs-sample-$(tt.params.git-revision)
      - name: dockerfile
        value: Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:3dddea8074c9fa13e7146e3c5c7d75e4bd8f7bb0
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: nodejs-sample/$(tt.params.git-revision)
    status: {}
status: {}
